language: node_js
node_js:
  - "node"
  - "lts/*"

deploy:
  provider: script
  script: "npm run build"
  skip_cleanup: true
  on:
    tags: true

notifications:
  email:
    recipients:
    - khensolomon@gmail.com
    on_success: change
    on_failure: always